"""Build the closed English vocabulary behind the undecided plain-ASCII exception.

Writes ``laya/english_lexicon.py`` and ``laya-ts/src/english-lexicon.ts`` from Peter
Norvig's word counts for the Google Trillion Word Corpus. The rule, in order:

1. the first ``TOP_N`` (10,000) rows of ``count_1w.txt``, in its frequency order;
2. drop one-letter tokens other than ``a`` and ``i`` (they are initials, not words);
3. drop the words in ``EXCLUDED`` below.

The output keeps frequency-rank order, so the depth argument in the docstring
(``playlist`` sits past rank 7,000) can be checked against the file itself.

Usage::

    python scripts/build_english_lexicon.py                 # download, verify, write
    python scripts/build_english_lexicon.py --source FILE   # use a local copy instead
    python scripts/build_english_lexicon.py --check         # exit 1 if the files differ

norvig.com sometimes answers scripted downloads with a browser check page instead of the
file. The checksum below catches that. The same bytes are archived at
http://web.archive.org/web/20250114182717id_/https://norvig.com/ngrams/count_1w.txt
(served gzip-encoded, so use ``curl --compressed``); download that and pass it with
``--source``.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
import urllib.request

SOURCE_URL = "https://norvig.com/ngrams/count_1w.txt"
# count_1w.txt as served with Last-Modified 2019-04-22 (333,333 lines).
SOURCE_SHA256 = "51df159fd3de12b20e403c108f526e96dbd723d9cabdd5f17955cdc16059e690"
TOP_N = 10_000
ONE_LETTER_KEPT = ("a", "i")

# Words removed from the top 10,000 on purpose, by category. Everything else in the top
# 10,000 stays, including ordinary words the corpus often saw on adult sites: mild oaths
# (damn, hell, bloody, crap), religion (god), anatomy with an everyday sense (breasts, balls,
# butt), general words (sex, sexy, hardcore, escort, squirt, suck), names (cox, jo, wang) and
# British spellings (colour, favourite, organised). Leaving a word out only moves text that
# contains it to the multilingual checkpoint.
#
# Six excluded words also have an innocent sense -- ass (donkey), cock (rooster), dick (name),
# pussy (cat), tit (bird), cum (Latin "with") -- but the obscene sense dominates in this corpus.

# Profanity: vulgar swear words and vulgar slang for body parts or people.
_PROFANITY = """
    ass bitch boob boobs cock cocks cunt dick dicks fuck fucked fucking piss pissing pussy shit
    slut sluts tit tits whore
"""
# Sexually explicit terms and porn site names: words whose use here is sexual content.
_SEXUALLY_EXPLICIT = """
    anal bangbus bbw bdsm beastiality bestiality blowjob blowjobs bondage bukkake busty cum
    cumshot cumshots dildo dildos ejaculation erotic fingering fisting gangbang handjob handjobs
    hentai horny incest livesex lolita masturbating masturbation milf milfhunter milfs nipple
    nipples nude nudity orgasm orgy panties penis playboy porn porno rape sexcam sexo squirting
    threesome topless twinks upskirt upskirts vagina viagra vibrator vibrators voyeur worldsex
    xnxx xxx zoophilia
"""
# Slurs: words that demean people for who they are.
_SLURS = """
    shemale shemales tranny
"""
EXCLUDED = frozenset((_PROFANITY + _SLURS + _SEXUALLY_EXPLICIT).split())


REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PY_OUT = os.path.join(REPO, "laya", "english_lexicon.py")
TS_OUT = os.path.join(REPO, "laya-ts", "src", "english-lexicon.ts")


def read_source(path: str | None) -> bytes:
    if path:
        with open(path, "rb") as f:
            data = f.read()
    else:
        req = urllib.request.Request(SOURCE_URL, headers={"User-Agent": "laya-lexicon-build"})
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = resp.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SOURCE_SHA256:
        raise SystemExit(f"count_1w.txt sha256 is {digest}, expected {SOURCE_SHA256} "
                         "(see the module docstring)")
    return data


def build(data: bytes) -> list:
    ranked = [line.split("\t", 1)[0] for line in data.decode("utf-8").splitlines() if line]
    top = ranked[:TOP_N]
    words = [w for w in top if len(w) > 1 or w in ONE_LETTER_KEPT]
    missing = EXCLUDED.difference(words)
    if missing:
        raise SystemExit(f"EXCLUDED lists words outside the top {TOP_N}: {sorted(missing)}")
    return [w for w in words if w not in EXCLUDED]


def render_python(words: list) -> str:
    n_one = TOP_N - len(words) - len(EXCLUDED)
    head = '''"""Closed English vocabulary for one routing exception.

Generated by ``scripts/build_english_lexicon.py``; do not edit by hand. The
source is Peter Norvig's count of the Google Trillion Word Corpus
(https://norvig.com/ngrams/count_1w.txt, sha256 pinned in the script). The
rule: take the {top} most frequent word forms, drop the {n_one} one-letter
tokens other than ``a`` and ``i``, then drop the {n_ex} words in the script's
``EXCLUDED`` list (profanity, sexually explicit terms and porn site names,
and slurs; the script says what is and is not excluded). That leaves {n}
words, stored in frequency-rank order.

``laya.lang`` already names English from a single function word, so this set
is consulted only when that guess stays undecided: plain-ASCII text of four or
more words stays on the English checkpoint when every word is here.

``playlist`` is past rank 7,000, so a shorter prefix of the same list would
miss the commands the exception exists for. A possessive ``'s`` is split off
by the word pattern and is not stored here; a plural ``s`` is handled by the
caller.
"""

ENGLISH_LEXICON = frozenset(
    """
'''.format(top=f"{TOP_N:,}", n_one=n_one, n_ex=len(EXCLUDED), n=f"{len(words):,}")
    return head + "\n".join(words) + '\n    """.split()\n)\n'


def render_ts(words: list) -> str:
    head = """/** Closed English vocabulary for one routing exception.
 *
 * Generated by `scripts/build_english_lexicon.py`; do not edit by hand. Same
 * words, in the same frequency-rank order, as `laya/english_lexicon.py`: the
 * {top} most frequent word forms in Norvig's `count_1w.txt`, without the
 * {n_one} one-letter tokens other than `a` and `i` and without the {n_ex} words
 * in the script's `EXCLUDED` list. {n} words.
 */
export const ENGLISH_LEXICON_TEXT = `
""".format(top=f"{TOP_N:,}", n_one=TOP_N - len(words) - len(EXCLUDED),
           n_ex=len(EXCLUDED), n=f"{len(words):,}")
    return head + "\n".join(words) + """
`;

export const ENGLISH_LEXICON: ReadonlySet<string> = new Set(
  ENGLISH_LEXICON_TEXT.split(/\\s+/).filter((w) => w.length > 0),
);
"""


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--source", help="local copy of count_1w.txt (default: download SOURCE_URL)")
    ap.add_argument("--check", action="store_true", help="compare instead of writing")
    args = ap.parse_args(argv)

    words = build(read_source(args.source))
    outputs = {PY_OUT: render_python(words), TS_OUT: render_ts(words)}
    stale = []
    for path, text in outputs.items():
        current = ""
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        if current != text:
            stale.append(os.path.relpath(path, REPO))
            if not args.check:
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(text)
    n_one = TOP_N - len(words) - len(EXCLUDED)
    print(f"{len(words):,} words: top {TOP_N:,}, {n_one} one-letter tokens dropped, "
          f"{len(EXCLUDED)} excluded")
    if args.check and stale:
        print("out of date: " + ", ".join(stale), file=sys.stderr)
        return 1
    if not args.check:
        print("rewrote: " + (", ".join(stale) or "nothing, already current"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
